### ISSUE TITLE
params vs trailing

### ISSUE THREAD

**Issue by grawity** [Detegr/RBot#1]
I noticed the RBot parser considers |params| and |trailing| to be separate fields in the final `struct Message`, although it is [explicitly](https://tools.ietf.org/html/rfc1459#section-2.3.1) [specified](https://tools.ietf.org/html/rfc2812#section-2.3.1) that after parsing they should be merged.

This might create problems later, when dealing with different servers. For example, the following are equivalent, and you can see both versions in the wild:

```
:src JOIN #chan
:src JOIN :#chan
```

As the protocol description says "‹trailing› is just a syntactic trick to allow SPACE within the parameter", it wouldn't be incorrect for a server to decide between the two versions dynamically, based on whether the parameter has spaces.

There have been some vague attempts to have [standard test cases](https://github.com/ircv3/ircv3-specifications/issues/104#issuecomment-97567926) in case that's relevant.

---

As a side note, it would be interesting to also parse [v3.2 message tags](http://ircv3.net/specs/core/message-tags-3.2.html).

**Comment by Detegr** [comment]
Thank you for this issue! I haven't read the RFC very thoroughly. This is something that needs to be changed for sure.
